version: "3.8"
services:
  db:
    image: postgres:13.3-alpine3.14
    container_name: docker_db_1
    ports:
      - "6543:5432"
    restart: on-failure
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - "postgres:/var/lib/postgresql/data:cached"
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  kafka:
    image: docker.io/bitnami/kafka:3.1.0
    container_name: docker_kafka_1
    restart: on-failure
    ports:
      - 9092:9092
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  zookeeper:
    image: bitnami/zookeeper:3.7
    container_name: docker_zookeeper_1
    restart: on-failure
    ports:
      - 2181:2181      
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper:/bitnami/zookeeper
  messenger:
    build:
      context: .
    restart: "on-failure"
    container_name: docker_messenger_1
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
    volumes:
      - $HOME/projects:/projects/:cached
      - "messenger:/go/pkg/:cached"
    working_dir: "/projects/messenger"

volumes:
    postgres:
    kafka:
    zookeeper:
    messenger: